### ISSUE TITLE
cannot load such file -- zip

### ISSUE THREAD

**Issue by halostatue** [rubycocos/text#2]
At [textutils.rb:15](https://github.com/textkit/textutils/blob/master/lib/textutils.rb#L15), you `require 'zip'` which does not work if you have an older version of rubyzip installed (pre 1.0), because that version of `rubyzip` defines its load at `zip/zip`.

I suggest that the `rubyzip` dependency at [Rakefile:24](https://github.com/textkit/textutils/blob/master/Rakefile#L24) be modified to require at least 1.0.

**Comment by geraldb** [comment]
Great catch. Thanks. Will do.Cheers.

**Comment by geraldb** [comment]
FYI: The latest gem, that is, v1.4.0 includes your change. Thanks again. Cheers.
